### PR TITLE
Tempfile fix for issue-37

### PR DESCRIPTION
**Pull request by whiskeyriver**
This fixes the tempfile race, but introduces a dependency on https://github.com/djberg96/file-temp

### CODE REVIEW

**Comment by ejholmes** [comment]
Thanks! I'll review this later in the day.

**Comment by ejholmes** [comment]
Finally got a chance to look at this. I think I'd prefer an implementation that doesn't introduce another dependency. Should be able to get around the race condition by using a block to pass the path. Something like this maybe:

``` ruby
def extract_to(destination)
  return on_complete { |job| job.extract_to(destination) } unless started?
  with_tmp_zip_file do |path|
    unzip(path, destination)
  end
  self
end

private

def unzip(source, destination)
  Zip::ZipFile.open(source) do |zip|
    zip.each do |f|
      path = File.join(destination, f.name)
      FileUtils.mkdir_p(File.dirname(path))
      zip.extract(f, path) { true }
    end
  end
end

def with_tmp_zip_file
  file = Tempfile.new('retrieve')
  file.write(zip_file)
  yield file.path
  file.close
end
```

**Comment by whiskeyriver** [comment]
Aha! I knew there had to be a better way. I'm still new to ruby.

**Comment by ejholmes** [comment]
Fixed in 3e88e91

**Pull request closed without merging**
